# Generated by Django 5.1 on 2024-08-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='subject',
            field=models.TextField(max_length=30),
        ),
    ]
