# Generated by Django 5.1 on 2024-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_blog_description_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
