# Generated by Django 5.1 on 2024-12-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_titlei'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleI',
        ),
    ]
